id: IA36AFE33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:51:11+00:00'
last_modified: '2022-06-08T04:37:49.056524+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14649
  title: སྲོང་བཙན་ཚངས་དབྱངས། ༼དུས་དེབ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    949D:
      image_group_id: I1KG15715
      title: ''
      total_pages: 41
      order: 1
      base_file: 949D.txt
    C08B:
      image_group_id: I1KG15716
      title: ''
      total_pages: 60
      order: 2
      base_file: C08B.txt
    9EE4:
      image_group_id: I1KG15717
      title: ''
      total_pages: 58
      order: 3
      base_file: 9EE4.txt
    1B93:
      image_group_id: I1KG15718
      title: ''
      total_pages: 64
      order: 4
      base_file: 1B93.txt
    '9538':
      image_group_id: I1KG15719
      title: ''
      total_pages: 64
      order: 5
      base_file: 9538.txt
    6A4B:
      image_group_id: I1KG15720
      title: ''
      total_pages: 70
      order: 6
      base_file: 6A4B.txt
    '6851':
      image_group_id: I1KG15721
      title: ''
      total_pages: 56
      order: 7
      base_file: 6851.txt
    A204:
      image_group_id: I1KG15722
      title: ''
      total_pages: 64
      order: 8
      base_file: A204.txt
    BFBB:
      image_group_id: I1KG15723
      title: ''
      total_pages: 60
      order: 9
      base_file: BFBB.txt
    0CCC:
      image_group_id: I1KG15724
      title: ''
      total_pages: 54
      order: 10
      base_file: 0CCC.txt
    D74F:
      image_group_id: I1KG15725
      title: ''
      total_pages: 56
      order: 11
      base_file: D74F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
